### ISSUE TITLE
 输入框 长按会报错

### ISSUE THREAD

**Issue by liaoli** [Im-Kevin/cool_ui#53]
The following NoSuchMethodError was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#ce416](dirty, dependencies: [MediaQuery], state: _OverlayEntryWidgetState#61a44):
The getter 'cutButtonLabel' was called on null.
Receiver: null
Tried calling: cutButtonLabel

The relevant error-causing widget was: 
  Overlay file:///Users/mac/Downloads/cool_ui-master/lib/keyboards/keyboard_root.dart:33:20
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _CupertinoTextSelectionControls.buildToolbar (package:flutter/src/cupertino/text_selection.dart:365:44)
#2      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:556:34)
#3      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:177:34)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)

**Comment by Im-Kevin** [comment]
你是什么版本

**Comment by liaoli** [comment]
最新版本，你的demo也会这样

**Comment by liaoli** [comment]
有没有解决方案啊
