### ISSUE TITLE
在 mac 平台弹出键盘后任意点击操作都会关闭键盘

### ISSUE THREAD

**Issue by ixugo** [Im-Kevin/cool_ui#72]
``cool_ui : 1.1.0
flutter   : 2.5.0
系统      : MacOS 11

我在 mac 平台使用此库时，遇到异常，在弹出键盘后点击任意按钮会导致键盘关闭。希望能够获得帮助，错误详情如下:

`════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
A KeyboardController was used after being disposed.

Once you have called dispose() on a KeyboardController, it can no longer be used.
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:114
#1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:120
#2      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:288
#3      ValueNotifier.value=
package:flutter/…/foundation/change_notifier.dart:412
#4      KeyboardController.value=
package:cool_ui/keyboards/keyboard_controller.dart:50
#5      KeyboardController.addText
package:cool_ui/keyboards/keyboard_controller.dart:107
#6      KeyModel.addText
package:music_keyboards/keyboards/key_model.dart:89
#7      BuildButton._onTap
package:music_keyboards/keyboards/key_style.dart:159
#8      BuildButton._buildButton.<anonymous closure>
package:music_keyboards/keyboards/key_style.dart:306
#9      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:989
#10     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:193
#11     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:608
#12     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
#13     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:267
#14     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#15     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:444
#16     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:420
#17     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:278
#18     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#19     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#20     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#21     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#25     _invoke1 (dart:ui/hooks.dart:185:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#342f9
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(135.1, 460.0)
    finalLocalPosition: Offset(48.1, 27.0)
    button: 1
    sent tap down
`

**Comment by ixugo** [comment]
已解决!  将 KeyboardRootWidget 放在 main 函数中。
