### ISSUE TITLE
同一个页面两个输入框切换输入报错

### ISSUE THREAD

**Issue by Xmaoyh** [Im-Kevin/cool_ui#82]
`======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
A KeyboardController was used after being disposed.

Once you have called dispose() on a KeyboardController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
#4      KeyboardController.value= (package:cool_ui/keyboards/keyboard_controller.dart:50:11)
#5      KeyboardController.addText (package:cool_ui/keyboards/keyboard_controller.dart:107:5)`

输入完一个再点击另一个输入时，报错。

**Comment by Xmaoyh** [comment]
> 这两个是同一个键盘吗

是的

**Comment by jianchao97** [comment]
Hi,

I encounter the same error when I convert my keyboard become `Stateful Widget` and assign the keyboard controller to a `late` variable. 
![image](https://github.com/Im-Kevin/cool_ui/assets/34544848/fcc786cc-9ff8-4ccb-bf70-33bcd234b7d6)

However, I am able to resolve the error if I remove the `late` variable and directly use the `widget.controller`. 
![image](https://github.com/Im-Kevin/cool_ui/assets/34544848/98670fcf-b388-4920-88d8-5dbedf433ee6)

I'm not sure what is the root cause and why the error was gone after removing the late variable.  Maybe you can try to do the same thing to eliminate the error. 

Please also share me if you found the reason or root cause. 

Thankss!
